<a href="https://colab.research.google.com/github/arun-arunisto/Python-Education/blob/todo/NumpyTutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://numpy.org/doc/stable/_static/numpylogo.svg" width="200"/>
<h2>Numpy Beginner's Guide</h2>
<p><i>Arun Arunisto</i><p>

<ul>
<li>What is Numpy?</li>
<p align="justify">NumPy (Numerical Python) is an open-source Python library that’s used in almost every field of science and engineering. The NumPy library contains multidimensional array and matrix data structures. It provides ndarray, a homogeneous n-dimensional array object, with methods to efficiently operate on it. NumPy can be used to perform a wide variety of mathematical operations on arrays. The NumPy API is used extensively in Pandas, SciPy, Matplotlib, scikit-learn, scikit-image and most other data science and scientific Python packages.</p>
<li>Installing Numpy</li>
</ul>

In [2]:
!pip install numpy 
#not need ! to install numpy on windows, 
#or other platforms you can execute simply "pip install numpy"

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [5]:
import numpy as np
#accessing numpy in Python

<ul>
<li>Why use numpy?</li>
<p align="justify">NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.</p>
</ul>

In [6]:
#creating an basic array
basic_array = np.array([1, 2, 3])
basic_array

array([1, 2, 3])

In [7]:
#creating an 2D array
two_d = np.array([[1, 2, 3], [4, 5, 6]])
two_d

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
#creating an array filled with 0's
zeros = np.zeros(4)
zeros

array([0., 0., 0., 0.])

In [10]:
#creating an array filled with 1's
ones = np.ones(4)
ones

array([1., 1., 1., 1.])

In [12]:
#create an empty array with 4 elements
#the result will be vary
empty = np.empty(4)
empty

array([1., 1., 1., 1.])

In [13]:
#creating an array using range
range_ = np.array(range(1, 5))
range_

array([1, 2, 3, 4])

In [17]:
#concatenating two arrays
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
concate = np.concatenate((a1, a2))
concate

array([1, 2, 3, 4, 5, 6])

<p>* To find dimension, shape, size of an array</p>

In [18]:
#sample array
sam = np.array([[[24, 45, 66, 78]], 
                [[77, 86, 94, 36]],
                [[28, 53, 71, 90]]])
sam

array([[[24, 45, 66, 78]],

       [[77, 86, 94, 36]],

       [[28, 53, 71, 90]]])

In [19]:
#to find the number of dimensions
sam.ndim

3

In [20]:
#to find the shape
sam.shape

(3, 1, 4)

In [21]:
#to find the size
sam.size

12

<p>* Most useful array operations</p>

In [23]:
#to find maximum
sam.max()

94

In [24]:
#to find minimum
sam.min()

24

In [25]:
#to find sum
sam.sum()

748

<p>* generating array with random numbers</p>

In [29]:
#generating array with random numbers
#from 1, 10 in the shape of 2x4
rng = np.random.default_rng() #to generate random numbers
ran = rng.integers(10, size=(2, 4))
ran

array([[0, 6, 3, 5],
       [1, 0, 2, 1]])

<p>* getting unique items</p>

In [30]:
arr = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
uni = np.unique(arr)
uni

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

<p>* Reversing an array</p>

In [31]:
#reverse an array
rev = np.flip(uni)
rev

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

<p>* Saving and load numpy objects</p>

In [33]:
#saving a numpy object
np.save("reverse", rev) 
#it will save as reverse.npy 

In [34]:
#loading an numpy file
file_ = np.load("reverse.npy")
file_

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11])